
    default: &default
      adapter: postgresql
      encoding: unicode
      host: <%= ENV['host_postgres'] %>
      port: <%= ENV['port_postgres'] %>
      username: <%= ENV['username_postgres'] %>
      password: <%= ENV['password_postgres'] %>
      pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

    development:
      <<: *default
      database: csvimport_development

    test:
      <<: *default
      database: csvimport_test

    production:
      <<: *default
      database: csvimport_production
      username: csvimport
      password: <%= ENV['csvimport_DATABASE_PASSWORD'] %>
